// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkm3aKDhYPi9LlZYzrDKkH9Day-WjyuOU',
    appId: '1:6875036844:web:653a9d8aaca914ab337309',
    messagingSenderId: '6875036844',
    projectId: 'shopping-app-c11a4',
    authDomain: 'shopping-app-c11a4.firebaseapp.com',
    databaseURL: 'https://shopping-app-c11a4-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-app-c11a4.firebasestorage.app',
    measurementId: 'G-SBNSC4GQ15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlMvYJPenkyEKyKHxL_zGrYxVNvFmmdik',
    appId: '1:6875036844:android:8f8a317e4951540d337309',
    messagingSenderId: '6875036844',
    projectId: 'shopping-app-c11a4',
    databaseURL: 'https://shopping-app-c11a4-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-app-c11a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt2PxpEoA1kAdQCp6uJPQ_VUp0gPK2co0',
    appId: '1:6875036844:ios:728f39f0f095003b337309',
    messagingSenderId: '6875036844',
    projectId: 'shopping-app-c11a4',
    databaseURL: 'https://shopping-app-c11a4-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-app-c11a4.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt2PxpEoA1kAdQCp6uJPQ_VUp0gPK2co0',
    appId: '1:6875036844:ios:728f39f0f095003b337309',
    messagingSenderId: '6875036844',
    projectId: 'shopping-app-c11a4',
    databaseURL: 'https://shopping-app-c11a4-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-app-c11a4.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkm3aKDhYPi9LlZYzrDKkH9Day-WjyuOU',
    appId: '1:6875036844:web:15f627cac8351f72337309',
    messagingSenderId: '6875036844',
    projectId: 'shopping-app-c11a4',
    authDomain: 'shopping-app-c11a4.firebaseapp.com',
    databaseURL: 'https://shopping-app-c11a4-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-app-c11a4.firebasestorage.app',
    measurementId: 'G-W71G128BRN',
  );
}
